CREATE TABLE [dbo].[tblSeguranca](
	[idToken] [int] IDENTITY(1,1) NOT NULL,
	[Token] [varchar](250) NOT NULL,
	[DataGeracao] [DateTime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idToken] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO